### ISSUE TITLE
getY(): mapping of Y coordinate

### ISSUE THREAD

**Issue by huttarl** [leahbuechley/Turtle#1]
Thank you for implementing this library and making it freely available. My daughters are learning about programming and about curves like Koch's snowflake, Heighway Dragon, and others, so having a turtle library for Processing is very handy for them.

It came as a surprise, and a confusing source of bugs, that getY() didn't return the Y coordinate that matched what the turtle was drawing on the screen. I.e. the turtle uses a different Y axis from Processing. Through trial and error, I discovered that in order to get the expected Y value in the default coordinate system, you have to take `height - t.getY()`. This should be [documented](http://leahbuechley.com/Turtle/reference/getY.html). I won't advocate for changing it -- it seems like an intentional choice, and I'm sure it's a can of worms.

The same issue applies to other methods that feature a Y value as input or output, e.g. `setY()` and `goToPoint()`.

**Comment by leahbuechley** [comment]
Sorry for the extremely belated reply! This is now fixed.
